package Ejercicio4;

//ABSTRACCION POOO


//CLASES ABSTRACTAS SE USA ABSTRACT, ES LA CLASE PADRE QUE LES INDICA A SUS CLASES HIJAS CUALES FUNCIONALIDADES DEBEN IMPRELEMTAR
//OBLIGATORIAMENTE



//TODAS LAS CLASES QUE SE EXTIENDAN DE ESTA CLASE TIENEN QUE TENER EL METODO calcularArea();
public abstract class Figura {


    //METODOS ABSTRACTOS QUE VAN A HEREDAR LOS HIJOS
    public abstract double calcularArea();
    //SOLO SE DECLARAN AQUI Y SE EJECUTAN LAS CLASES EN LAS HIJAS YA QUE OBLIGA A SU HIJA A TENER ESTE METODO
}
